### ISSUE TITLE
Provide better customization for inactive buffers

### ISSUE THREAD

**Issue by aravind2612krishna** [datwaft/bubbly.nvim#53]
While I love the simplicity and looks of this plugin, I cannot use it due to the lack of customization of inactive buffers

Please provide documentation on how to customize inactive buffer colors.

**Comment by datwaft** [comment]
Good idea.

Currently there is no way to customize inactive buffers mainly because I forgot people would want to customize them.

I will add a way to change the colors and maybe even the style of the inactive buffers, and the proper documentation.

Something curious I found about inactive buffers is that part of the statusline must be hidden, like the paste bubble, because they are technically global (when changing buffers in changes to the one of the active buffer), it seems, if you or anyone knows how to make that local and stay in that buffer state feel free to tell me.

Thanks for your idea! I will implement this in the next few days.

**Comment by datwaft** [comment]
Done!

**Comment by aravind2612krishna** [comment]
The setting documented is inactive_color, but the actual change is done by bubbly_inactive_color
![image](https://user-images.githubusercontent.com/3424615/103856965-91da6100-50db-11eb-82a8-173eb65bce14.png)
![image](https://user-images.githubusercontent.com/3424615/103857160-f1d10780-50db-11eb-9c57-aa639f5d7db3.png)

**Comment by datwaft** [comment]
Ah, my bad, sorry.

**Comment by datwaft** [comment]
Fixed
