### ISSUE TITLE
Reload/recompute on colorscheme change is not working

### ISSUE THREAD

**Issue by cinghiopinghio** [datwaft/bubbly.nvim#61]
Hi,

In `bubbly.factories.highlight` you add an `autocommand` on `ColorScheme` and `VimEnter` which redefine all the highights computed by your factory. But there is no point to re-apply highlightings on `ColorScheme` change since your defined highlights won't be changed.

It would maybe be helpful to actually recompute entirely all colors highlights so that one can eventually write some function that adapt the statusline colors to the new theme.

In particular I was trying to add a small functionality to your code that extract the necessary colors from the `User1..9` colorscheme highlights (plus `Statusline`).
This would automatically adapt the statusline colors to the new colorscheme if the colorscheme support those highlights, of course.

Thoughts?

PS.I also noticed that you are adding `autocommands` in `bubbly.vim` that compute on `CursorHold` the current function even if it is not required by the user confguration. Can this be checked before adding the `autocommand`?

**Comment by datwaft** [comment]
> In bubbly.factories.highlight you add an autocommand on ColorScheme and VimEnter which redefine all the highights computed by your factory. But there is no point to re-apply highlightings on ColorScheme change since your defined highlights won't be changed.

Originally I only used `VimEnter` as an autocommand, but then I saw that the statusline lost all colors every time I changed the colorscheme. I am going to check if this is still necessary or not.

> It would maybe be helpful to actually recompute entirely all colors highlights so that one can eventually write some function that adapt the statusline colors to the new theme.
>
> In particular I was trying to add a small functionality to your code that extract the necessary colors from the User1..9 colorscheme highlights (plus Statusline).
> This would automatically adapt the statusline colors to the new colorscheme if the colorscheme support those highlights, of course.
>
> Thoughts?

That would be nice. Originally I didn't use User1..9 in my plugin because I didn't know how they worked, so being able to extract the highlights would be wonderful.

Also, I need to check why it doesn't recompute; originally my intention was for it to recompute.

> PS.I also noticed that you are adding autocommands in bubbly.vim that compute on CursorHold the current function even if it is not required by the user confguration. Can this be checked before adding the autocommand?

That one was added by @PatOConnor43. I forgot to add a check to only load autocommands when neccesary. Maybe I will add a folder that contains `.lua` files and that is loaded everytime a module with the same name is loaded, as an autocommand.

**Comment by cinghiopinghio** [comment]
It doesn't recompute because you construct the command with the already computed colors and than you feed it to the autocommand that is going to repeat it unchanged at every change of coloscheme.

I will PR my changes to let you know how to get the highlight colors.

**Comment by datwaft** [comment]
Thank you. I will need to investigate how to make it recalculate the highlights every time.

I will check this in a few days, today I am kinda busy.

**Comment by datwaft** [comment]
#73 should close this.
